import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import NavBer from "./components/shared/NavBer";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col  bg-fit-theme font-inter">
        <NavBer />
        {children}
      </body>
    </html>
  );
}
